apiVersion: v1
kind: Service
metadata:
  name: banking-details-service
  namespace: default
  labels:
    app: banking-details-service
spec:
  selector:
    app: banking-details-service
  ports:
    - port: 8083
      targetPort: 8083
  type: NodePort