apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-details-service
  namespace: default
  labels:
    app: banking-details-service
spec:
  replicas: 1
  template:
    metadata:
      name: banking-details-service
      labels:
        app: banking-details-service
        role: rolling-update
    spec:
      containers:
        - name: banking-details-service
          image: pradnyilk/banking-details-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
      restartPolicy: Always
  selector:
    matchLabels:
      app: banking-details-service
