spring:
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411/
  application:
    name: banking-details-service
  cloud:
    consul:
      host: consul-consul-server
      port: 8500
server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: "*"